//
//  FeedViewController.swift
//  FBtest --> cooresponds to Firebase Project: FBtest123
//
//  Created by eva on 2018/5/26.
//  Copyright © 2018年 Lextronic. All rights reserved.
//

import UIKit
import Firebase
import FirebaseDatabase
import FirebaseDatabaseUI   // To Optimize dataSource of UITableViewDatasource
import SDWebImage           // To Optimize the Photo-download process
// import SVProgressHUD

class FeedViewController: UITableViewController, UIImagePickerControllerDelegate, UINavigationControllerDelegate {

   var ref: DatabaseReference!  // see example in Firebase
   var postsRef: DatabaseReference!
   var dataSource: FUITableViewDataSource!
   override func viewDidLoad() {
        super.viewDidLoad()
        ref = Database.database().reference() // 取得 Firebase 的根目錄
        postsRef = ref.child("posts") // 根目錄 --> 新增 posts 目錄
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 410
        let query = postsRef.queryOrdered(byChild: "postDateReversed")
   
    // Attn: downLoad data from Firebase Database with FirebaseUI tool
        dataSource = tableView.bind(to: query) { tableView, indexPath, snapshot -> UITableViewCell in
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "PostCell", for: indexPath) as! PostCell
        // snapshot contains all data below postsRef
        if let postData = snapshot.value as? [String: Any] {
            cell.emailLabel.text = postData["email"] as? String
            let imageURLString = postData["imageURL"] as! String
            let imagURL = URL(string: imageURLString)!
            cell.photoImageView.sd_setImage(with: imagURL)
            }
            return cell
        }
     }
    //========================================================================
    //  2. 規劃本頁有一個取圖片按鈕跟首頁一樣:選擇照相機按鈕 --> 可以選圖庫或者是照相
    @IBAction func takePhotoTapped(_ sender: Any) {
        takePhoto()
    }
    //===================================================================
    //      4. 規劃取得了相片 UIImage 檔案, 傳到 Firebase Storage
    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        
        let image = info[UIImagePickerControllerOriginalImage] as! UIImage // 取得UIImage
        let postRef = postsRef.childByAutoId() // reference for each PhotoTaking which is generated by algorith
        let postKey = postRef.key   // key of reference for each PhotoTaking
        
        if Auth.auth().currentUser == nil {
            print("No peroson")
            return
        } // early return
        let currentUser = (Auth.auth().currentUser)!
        var postData: [String: Any] = [
            "authorUID": currentUser.uid,
            "email": currentUser.email!,
            "imagePath":"",
            "imageURL":"",
            "postDate": 0,
            "postDateReversed": 0,]
        
        if let imageData = UIImageJPEGRepresentation(image, 0.7){ //轉成  NSData, imageData is an optional
            let metadata = StorageMetadata()    // Create file metadata including the content type
            metadata.contentType = "image/jpeg"
            let imageRef = Storage.storage().reference().child("photos/\(postKey).jpg") //get content type
            let uploadTask = imageRef.putData(imageData, metadata: metadata) { metadata, error in
                guard let metadata = metadata else {
                    print("檔案上傳失敗")
                    return
                }
                print("上傳完成了")
                postData["imagePath"] = imageRef.fullPath
                // get imagePath in FirebaseStorage and put into FirebaseDatabase in line 119
                postData["imageURL"] = metadata.downloadURL()!.absoluteString // 需轉成 String
                // get imageURL in FirebaseStorage and put into FirebaseDatabase in line 120

                let now = Date ()
                let postDate = Int(round(now.timeIntervalSince1970 * 1000))
                postData["postDate"] = postDate
                postData["postDateReversed"] = -postDate
                debugPrint(metadata)
                postRef.updateChildValues(postData) // To create subdir "posts" and attached data in Firebase Database
                print(metadata.downloadURL()!)
            }
        }
        dismiss(animated: true, completion: nil)
    }
    
    @IBAction func signOutTapped(_ sender: Any) {
        try! Auth.auth().signOut()
        print (" 使用者登出")
        if let viewController = self.storyboard?.instantiateViewController(withIdentifier: "SigninFlow") {
            UIApplication.shared.keyWindow?.rootViewController = viewController
            self.dismiss(animated: true, completion: nil)
        }
    }
    
    func takePhoto(){
        let picker = UIImagePickerController() // build up an instance of UIImagePickerController
        picker.delegate = self          // self ViewController is the delegate class
        let actionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        
        //判斷有照相機功能 再規劃按鈕
        if UIImagePickerController.isSourceTypeAvailable(.camera){
            let cameraAction = UIAlertAction(title: "拍照", style: .default){ action in
                picker.sourceType = .camera
                self.present(picker, animated: true, completion: nil)
            }
            actionSheet.addAction(cameraAction) //加入照相機按鈕
        }
        //判斷有照片圖庫 再規劃按鈕
        if UIImagePickerController.isSourceTypeAvailable(.photoLibrary){
            let libraryAction = UIAlertAction(title: "選照片", style: .default){ action in
                picker.sourceType = .photoLibrary // 照片用選的
                self.present(picker, animated: true, completion: nil)
            }
            actionSheet.addAction(libraryAction)    //加入圖庫按鈕
        }
        
        let cancelAction = UIAlertAction(title: "Cancel", style: .cancel) { action in }
        actionSheet.addAction(cancelAction) //加入 cancell 按鈕
        present(actionSheet, animated: true, completion: nil)// 秀圖 actionSheet 3 按鈕
    }
}

